on: push

name: Continuous integration

jobs:
  check:
    name: cargo check
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: cat cargo config
        run: cat ~/.cargo/config

      - name: rustup toolchain list
        run: rustup toolchain list

      - name: cargo check
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: -vv
