on: push

name: Continuous integration

jobs:
  check:
    name: cargo check
    needs: dependencies
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check
